### ISSUE TITLE
Missing Step

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Azure-Stack#16]
Missing Step in Exercise 1- Task 1 -Sub task 6 - Step 11 in https://github.com/Microsoft/MCW-Azure-Stack/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Azure%20Stack.md#sub-task-6-install-the-app-service-resource-provider

After Step 11 user have to login in SQL Server and Run the following query in SQL Server Database.

**Comment by mwasham** [comment]
this step is already in the sept update
