### ISSUE TITLE
VM template no longer works correctly.

### ISSUE THREAD

**Issue by begler1** [Microsoft/MCW-Azure-Stack#22]
We executed this template several times during testing Dec 3-7 2018 and it worked well. We now execute it and the VM is not setup correctly. After deployment, AD, DNS and Hyper-V is not setup for AzureStack. Even Server Manager crashes when we click on Local Server. Please help!
![screenshot 3711](https://user-images.githubusercontent.com/22414394/52651054-7cda0080-2eb9-11e9-9c88-68cdede1bb58.png)
![screenshot 3712](https://user-images.githubusercontent.com/22414394/52651103-94b18480-2eb9-11e9-9687-c886ae7e9db9.png)

**Comment by begler1** [comment]
My bad. Looks like if I ignore all the errors in Server Manager and proceed with the install, it works OK. The security settings I was unable to see, were already set.

**Comment by DawnmarieDesJardins** [comment]
Issue resolved, closing
