### ISSUE TITLE
June 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Azure-Stack#25]
@mwasham @Jeff-Opsgility 
Hello,
This workshop is has been scheduled for a June 2019 content update.  Please have your author review open issue #24 and open pull requests #21 and #23 and add their suggestions to update the workshop inside of this issue.  Once done, I'll request SME approval.  Due: EOD 5/14/19
Thanks, Dawnmarie

**Comment by mwasham** [comment]
The scenario is pretty complete as-is (and takes about 4.5 hours). I don't think we should add anything to it - but it does need a pretty solid update as all of the screens/flow is out of date.

**Comment by mattmcspirit** [comment]
I agree with Michael - i think the overall scenario is fine, and demonstrates a number of useful areas of the App Service. The _*only* aspect I'd consider at the end of the lab, is the PDF that's generated - it seems like it would benefit from more info than just what's captured today.

Outside of that, perhaps some advanced troubleshooting/investigation that involves KUDU, could be of interest.

For me though, while the instructions are useful, the setup experience is relatively uninteresting, so another option may be to instruct users to run my ASDK Configurator: https://github.com/mattmcspirit/azurestack. You could either guide someone through the execution steps, or simply remove the steps before this one: https://github.com/microsoft/MCW-Azure-Stack/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Azure%20Stack.md#task-2-register-resource-providers-in-the-tenant-subscription, and instruct people to deploy an ASDK, then run the ASDK Configurator to setup their system ahead of the lab. You'd adjust the remaining steps to fit in with the way my ASDK Configuration names thing, subscription names, host names etc, just so things line up.

If you choose to keep the manual steps, they likely need review and update to reflect the later builds of Azure Stack.

**Comment by ChongRX78** [comment]
@mwasham - what do you think about @mattmcspirit's suggestions above?

**Comment by kevinsul** [comment]
Sorry for my tardy input, but agree with Matt's suggestions above.  I used the MCW workshop for a ~6 hour 1-day event a few months back by modifying the labs to exclude the setup experience as I had no time for it and is not very interesting/useful to learn about HOW you can use Azure Stack (we had ASDK nodes set up and ready to go ahead of the workshop - courtesy of Mr. McSpirir!).

**Comment by DawnmarieDesJardins** [comment]
@mwasham @paulopsgility 
Michael/Paul - brining this back up to your attention.

**Comment by paulopsgility** [comment]
I like the idea of adding some troubleshooting to the lab. 

As for setup and using ASDK, I am all for anything that makes the lab setup a better setup experience!

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham @ChongRX78 @waltermyersiii @hopero929 

So, in summary, this is what the June update will include:
 - review open issue #24 and open pull requests #21 and #23 and add their suggestions to update the workshop
 - update all screens/flow that is out of date
 - add advanced troubleshooting/investigation that involves KUDU
 - add and instruct users to run an ASDK Configurator for the lab set up

Have I captured everything correctly?  Leads, may Opsgility move forward with these improvements?

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham 
Lead sign-off received.  Please move forward with the update incorporating changes above.
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue with June 2019 update merge
