### ISSUE TITLE
Script name and Parameters have changed for ASDK Configurator impacting Before Hol-LAB

### ISSUE THREAD

**Issue by evmoreno** [microsoft/MCW-Azure-Stack#27]
https://github.com/mattmcspirit/azurestack/blob/master/deployment/AzSPoC.ps1

.\AzSPoC.ps1 -azureDirectoryTenantName "" -authenticationType "" -downloadPath "" -ISOPath "" -asdkHostPwd "" -VMpwd "" -azureAdUsername "" -azureAdPwd "" -useAzureCredsForRegistration -azureRegUsername "" -azureRegPwd "" -azureRegSubId ""

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility
Hi Paul, 
Please review & advise.  Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing with recent content update
