### ISSUE TITLE
Azure Stack Hub Operations before the hands-on lab setup guide

### ISSUE THREAD

**Issue by mysoultan** [microsoft/MCW-Azure-Stack#44]
I have done with installation the ASDK, and in Azure Stack Hub Operations before the hands-on lab setup guide, Do I need re-install everything for the operations part on a separate environment or Should I jump to Prepare the Azure Stack Hub Operator Station task install appropriate VSCode extensions and continue till I register the ADSK with the subscription?

**Comment by paulopsgility** [comment]
Yes, these are different MCWs so they require different setup.

**Comment by DawnmarieDesJardins** [comment]
Thanks for the response Paul, closing as complete
