### ISSUE TITLE
Update syntax PowerShell script

### ISSUE THREAD

**Issue by evmoreno** [microsoft/MCW-Azure-Stack#46]
https://github.com/microsoft/MCW-Azure-Stack/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Azure%20Stack%20Migrate.md#task-4-download-and-run-the-azure-stack-hub-configurator-script

7. From the Administrator: Windows PowerShell window, execute the script to configure the Azure SDK (ensure you replace the placeholder values, where [azure-admin-upn] and [azure-admin-password] designate the user name and password of the account with the Owner role in the Azure subscription you are using in this lab and the Global Administrator role in the Azure AD tenant associated with that subscription, [tenant] is the name of the Azure AD tenant associated with the Azure subscription you are using in this lab, and [subscription-id] is the identifier of that subscription):

 .\AzSPoC.ps1 -azureDirectoryTenantName '[tenant].onmicrosoft.com' -authenticationType AzureAD `
-downloadPath 'D:\ASDKfiles' -ISOPath 'D:\WS2016EVALISO.iso' -asdkHostPwd 'demo@pass123' -VMpwd 'demo@pass123' `
-azureAdUsername '[azure-admin-upn]' -azureAdPwd '[azure-admin-password]' -registerAzS -useAzureCredsForRegistration `
-azureRegSubId '[subscription-id]'-branch 'master'

Note * use of "" results in script failure instead replace with ''

**Comment by mwasham** [comment]
hi @evmoreno - can you clarify with more details? I'm not sure where/what is failing.

**Comment by DawnmarieDesJardins** [comment]
@evmoreno 
Hi Ev!  Were you able to get past this step?  If not, our authors need some more information.  Thank you!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no response from field.  Please reopen if you are still having an issue and can provide requested information.  Thankyou!
