### ISSUE TITLE
Get-AADToken : Exception calling "AcquireToken" with "3" argument(s): "Sequence contains no elements"

### ISSUE THREAD

**Issue by tayou0107** [microsoft/MCW-Azure-Stack#47]
Hi All,
I keep getting error in script number 4 during the HOL-Azure Stack Migrate.md.
Details are as follows.

[Script No. 4 on HOL-Azure Stack Migrate.md]
**.\Install-ASDK.ps1 -DownloadASDK -DeploymentType AAD -LocalAdminPass $localAdminPass -AADTenant [tenant].onmicrosoft.com -version '2002-35' -InfraAzureDirectoryTenantAdminCredential $azcred**
![image](https://user-images.githubusercontent.com/41351908/102423437-60c2bf80-404c-11eb-8546-988aa4165448.png)

But when i run the script i keep getting the error like below.
**Get-AADToken : Exception calling "AcquireToken" with "3" argument(s): "Sequence contains no elements"**
At C:\CloudDeployment\Setup\Common\AzureADConfiguration.psm1:198 char:14
+ ...    $token = Get-AADToken -ResourceUri $AzureURIs.ManagementServiceUri ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AADToken], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException,Get-AADToken

![image](https://user-images.githubusercontent.com/41351908/102423111-9e731880-404b-11eb-8d91-a9f59969c678.png)

I'm tracking the script in question, so I think the command below can't find the uri.
![image](https://user-images.githubusercontent.com/41351908/102423300-16d9d980-404c-11eb-8730-463d293998f6.png)

The accounts and subscriptions I tested,
Azure Internal subscriptions (with @microsoft.com and microsoft@onmicrosoft.com), MSDN subscriptions, and Free Trial subscriptions.
However, the Free Trial subscription couldn't grow to 20 cores, so I couldn't even deploy VMs.
And the subscription shown in the screenshot above is an MSDN subscription.

Can you give me any ideas?

**Comment by mwasham** [comment]
Hi there, it doesn't look like you are signing in with the Global Adin account for the tenant.. That's a requirement for installing the SDK.

**Comment by tayou0107** [comment]
> Hi there, it doesn't look like you are signing in with the Global Adin account for the tenant.. That's a requirement for installing the SDK.

**Comment by tayou0107** [comment]
> Hi there, it doesn't look like you are signing in with the Global Adin account for the tenant.. That's a requirement for installing the SDK.

Thanks for your help.
When I run the last command in script 1 of Before the HOL - Azure Stack Migrate.md, I am prompted to enter a public DNS name.
I entered 'azurestack' at this time, is this okay? Or do I need to enter a separate public DNS name?
![image](https://user-images.githubusercontent.com/41351908/102606723-86de8180-416a-11eb-8543-fd80273759bb.png)


If I type PublicDNSName as 'azurestack' and run script number 7, the following warning is generated and the script is stopped.

Is this the issue of publicDNSname?
![image](https://user-images.githubusercontent.com/41351908/102606937-dae96600-416a-11eb-9d54-2ea82acb566d.png)

**Comment by DawnmarieDesJardins** [comment]
Reopening issue so question can be answered.

**Comment by mwasham** [comment]
That will be the DNS name for the public IP of the Azure Stack host you are provisioning. You'll want to make it unique and specific to DNS host requirements (all lower case etc..)
