### ISSUE TITLE
Failed to deploy  Free SQL Server License: SQL Server 2017 Developer on Windows Server 2016 

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/MCW-Azure-Stack#8]
I was not able to deploy  Free SQL Server License: SQL Server 2017 Developer on Windows Server 2016 specified in Task 1 > Subtask 4.
It was showing an error : "failed to attach Disk to the VM".

**Comment by mwasham** [comment]
tested again and cannot repro
